sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  - openssl aes-256-cbc -K $encrypted_227a26790598_key -iv $encrypted_227a26790598_iv -in gcloud-service-account.json.enc -out gcloud-service-account.json -d

  - if [ ! d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-410.0.0-linux-x86_64.tar.gz;
    tar -xf google-cloud-cli-410.0.0-linux-x86_64.tar.gz;
    ./google-cloud-sdk/install.sh;
    fi

  - gcloud components install kubectl
  - gcloud version
  - gcloud auth activate service-account --key-file gcloud-service-account.json
  - gcloud config set project learn-k8s-370203
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials learn-k8s-cluster

  # - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  #   rm -rf $HOME/google-cloud-sdk;
  #   curl https://sdk.cloud.google.com | bash > /dev/null;
  #   fi
  # - source $HOME/google-cloud-sdk/path.bash.inc
  # - gcloud components update kubectl
  # - gcloud version
  # - gcloud auth activate-service-account --key-file gcloud-service-account.json
  # - gcloud config set project learn-k8s-370203
  # - gcloud config set compute/zone asia-southeast1-a
  # - gcloud container clusters get-credentials learn-k8s-cluster

script: true

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
