apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "quocdaitinls@gmail.com"
    privateSecretKeyRef:
      name: letsencrypt-prod
    solvers:
      selector:
        dnsNames:
          - learnk8s.tech
          - www.learnk8s.tech
      http01:
        ingress:
          class: nginx
