apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: loserforever/learn-k8s
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: redis_host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: redis_port
